name: block_skeleton
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Service locator
  get_it: ^7.7.0
  # Bloc for state management
  flutter_bloc: ^8.1.5
  # Value equality
  equatable: ^2.0.5

  # fpdart package: Functional programming thingies
  # fpdart package: Provides an easier way to follow the flow. You are forced to
  # handle the error case and you can't forget to handle it, like when you use
  # regular exceptions all over the place
  # https://pub.dev/packages/fpdart
  fpdart: ^1.1.0

  # Remote API
  internet_connection_checker: 1.0.0+1
  http: ^1.2.1
  # Local cache
  shared_preferences: ^2.2.3
  go_router: ^14.1.0

  # Packages folder
  util:
    path: packages/util/util
  exception:
    path: packages/core/exception
  app_ui:
    path: packages/presentation/app_ui

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4

flutter:
  uses-material-design: true